import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppBar, Box, Typography } from "@mui/material";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Quiz App</title>
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <header>
          <AppBar position="static" sx={{ bgcolor: "#4BC0C0" }}>
            <Typography variant="h6" component="div" sx={{ flexGrow: 1 }} p={2}>
              Quiz App
            </Typography>
          </AppBar>
        </header>


        {children}

      </body>
    </html>
  );
}
